apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jobhunt-staging

resources:
- ../../base
- configmap.yaml
- backend-sealed-secret.yaml
- postgres-sealed-secret.yaml
- minio-sealed-secret.yaml
- frontend-sealed-secret.yaml
- ingress.yaml

images:
- name: jobhunt-backend
  newName: ghcr.io/baalexandru/jobhunt-backend
  newTag: sha-14465af
- name: jobhunt-frontend
  newName: ghcr.io/baalexandru/jobhunt-frontend
  newTag: sha-14465af

patches:
- path: suspend-jobs.yaml

replicas:
- count: 0
  name: backend
- count: 0
  name: frontend
- count: 0
  name: redis
- count: 0
  name: postgres
- count: 0
  name: minio
