---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secrets
  namespace: jobhunt-staging
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCS1YSNOqM5IRX9yXgi6AjOpL4VY1rIAmrVMRR1zzR0XNGUED3SegBwMpQzHAtuk/MMnQiHUUqgx8LpGru2YIekDW6n/bj2w3gf0aFs9tLZ8u8mzORi1vkK/M52A6AOTLx5pAzVxiQspgGRJjI+qv7DFdQQaesEqGHaAOae22RxyH8oFORiBCb61x7K7/lGqEdpSr66hEV0oDFvMeQNWMs3IRFQ5ix7cKxkZcPXPg0+a8bavSoSr+HApcUAhfkNVIcIHfq8id7pS5MRpeZXCwalJ7PMOQYOR4dxtYBMogoQlJxIZAIMdqQLaTLDv/ymIVey4KlJ2108S8yWk30RudKsmZJraQU7LNQXjs3EOclIY/wdCnNepaMKhPkdc10IKtfhYvO3y6LGxF7MY7rsBCuVlVI+ysAjs3XW+PDHaSapka89t8H3Zny/0hR1uUULFrGjWCE0mP7c+83bwtxfnwYsgDBtVLeKPZRn6d03qbhzYa7o+/lhBYhIKYYERU1rGirqNZPxdhs7MnJrGnr3zUa5Drrt1/TCFHrUTQ8/g5T6luF52u3XwQM1Q5H2++klrFomG6nzi47Ub9miiD3VntcxBrAdH9k4BI0qjzDPQJ3P7uOWZbl6Y8GKOUciLMuNCAuizyGMH2oJpOXB7/9DYzl0fHSncWLwtYrLKwWh5GYgkalVcB3pfvWEKqf71n6PhPCB+NtnU9zjBMFtQ/2EOETC3tNAGd8AeKZ00yW+7qhiPFSmmwjQhBqffsKUBw==
    MINIO_ROOT_USER: AgCrYV79OPHxERfOcqDhISepjnl2vHjxrkw0liNY4EJVTR1y5+CIvSTB3vz+07TShDB0hqDf6HcS1ww07UHaYMualCHbWSGoCGzwk4L1GmzjUPEy9+b7QYiJc3xPCJgJCn3kgINznakonAmFAE87X974UuqkqaRCNWlTKxt5w9PQeJnWTz/lKyRvlfBaF78OGd6GWqen0riaOoWul7PQPITKRY2PzxRQYwcsPGBeimhFucQfxMQ9LPWpcKkFMbnx0Tr82M8rY7m3fcEcOT8Vqdkn1ENv6SPCfm+w2hWk/XgqWglobwB3rwZNECg28Wy2hMRXLoK7E8XektMEzqDojy5Dlx/2Lz0RhGZKD7rmKiLCEZNz1q9HIJZWD+CI+iBrus+7oByNP2WU/vO8zVfFsVpVBd2i50pbzGKyu/TcHplWmmrMjnVvECWRB+WqS1EO5CrvliNX7+YP9KGowFeCJ0WJwAgjn8ippXcaIT9cm9YVrSabJW+5S/8FVQJSTpM0I6N4h2HoBye6S2dMd02WBu8O2nIxCvlH2fWS0VMEYwkNCiCc4uAZGCSpZ2TTbvRQnUEqo60ZZyUQLzAuLYFRS9NkuOy8g3ZdBwOu9Vd01eNso0rsm+d+HEX1BHL/1EQ5lC8ZFXIeHzkDBVznIoQ7XiUkyDvF7hiqJw9CU0oAjmb3K4UCPpHCxnk3cbQpzGJjLauJkjMoshrCtPwpEoTRYX4rt5EVgtTxTxI=
  template:
    metadata:
      name: minio-secrets
      namespace: jobhunt-staging
