apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jobhunt-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:baalexandru/job-hunt.git
    targetRevision: master
    path: infra/k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: jobhunt-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
