apiVersion: v1
kind: Namespace
metadata:
  name: jobhunt-staging
  labels:
    environment: staging
    app.kubernetes.io/part-of: jobhunt
---
apiVersion: v1
kind: Namespace
metadata:
  name: jobhunt-prod
  labels:
    environment: production
    app.kubernetes.io/part-of: jobhunt
