---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-secrets
  namespace: jobhunt-prod
spec:
  encryptedData:
    BETTER_AUTH_SECRET: AgC8Gm883sI0jtLDG2XpmBw79EdgCD20+rwlfo0YSThk5sfidevKaM1XrPEZtk3w83LYrCiq86LNf/TOKU7HoYOlSkMW8oqrZ2JrQYSmqK1QSvv7zgGXLt8iR1Bo6Aa39lqk0vStPa0kjbpU4HwQgNzjmdfoKemJroiqNn/9dzZSsuuMQdVBW3wsJWSUnQSaM1Eu3OlOiprYMFXp6KzdqKt2nBl8U/Gt4rElQ79O/gFCCddWfWvX2+lg6/t0dixa0ZEfm0hAqi/DmdL9BouAoiiXkgrt7WVDlMgJlijUsMJqFnqf9plRGZKvbqT3c0LwdqYSaJhDUUVDoqRHVpYS9U5Df/j1vC2V2on9KVQNE5FOc9Bxs0o2QmYqeNwTeiCD/cs4MtzHVU0YPzqV/n17/PT8ZExwMzwPGYL8+zLEV2J4ZpTyDdMPgXnf0+5/jvh6GHIpWSkVN/GRkG9ZhOfhH97WLYfFAGxrV3WhuZV11WgGSvr3eVhyP6gjIt3fDpkHd0iM2HDayxGJORWPOzOgOptXHnLpe6GvU84ouhfFTKaWQU2yo6dSZfwuONCjbGYhM2eg1vyOMVOQA82vuPlM/pB8KUh8Q9GedtYqPd8e/NDhYkSSVEiDI4+myCZ1arrXyqCLJ1jt9qEkK6nPM4UAxf5hOitWVqPN9lvyx/QqwmZuOl/DAL2/cbCCohz1fScM/ChaXR79ZcgJ3HBGZ02xP4lRsmCPi9lSnrI1H+W9r25aR1g/6wjyhku6PlMiQg==
    DATABASE_URL: AgBRhGkJqrnaNDe+B+JF3CQM1w0aRFxx+g8zDYxE/yNyamfnSArHIxY2/IQKC27TNSEGSXHFTg+A2jC6pko+Bw1l8F09OsZ9bGZjc9hpmUkSwQZNngt1P6cj7Ii5jYg4d4hrll/RT/AQLwpFTgGumhARblSSwwbOesTD9jD1EKP61ccQEP+F45PyLIoMqsFPXcG7esb1er6JtnLlI8s5q80HXGK44Y6kTAoQg1kqj5QWrX2AT+axl7HPY41ATaj5qyw6i2MmRLzfSdlrBH7RYMkoW5KlhmA26Q29l3xuGXwU/pK0/e6e7Ovo/vxh4hdFJXZCoxWNW9zB3slMRxaF41DHJpo8PEgLM+jJlAtZHDNi4L/9kW+qvMNflKYCUSn5yiNJwcPIilPYT4nLT4GM6kexixHWJ11mlatKwT6MGnuWI/JDjPXUS3YhUUL3CdG0HNyMS+LPhZ1zrz18jsZg36/HN4cMWydbHd32qlAo4w0YwTaeSY6AJ5nWILBd/djL69/Mw13QWVAvReKECf4mrFGVEWYDSnaNvu/UdReXsyN7EFh6Q3kLO9+U3wDVXLiyXm0vp9se2PuxAh9OTBUorC0e3ivzMNhL7QaMjGfkrfYXscK/tjadX3GD4l/eamfiPooarzIxB8Jhh0vZ3j5VyXtsHHHqE4BgMEx7vwiiqG/1L+q1QEbffnat/j2Wx23gEGJAZyi+E+phPUFpx6llkyd+qlCJJLViqTG6psHwjpNUEv/mxqR56hTzbqYqzsSo4IdpaIYXqKtSIZ6zxovz+S3CL0rujzrpmrkP9mE=
  template:
    metadata:
      name: frontend-secrets
      namespace: jobhunt-prod
    type: Opaque
