---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-secrets
  namespace: jobhunt-prod
spec:
  encryptedData:
    BETTER_AUTH_SECRET: AgDBN+2tJ0JSNn58ZTcthYZ0S2HbZwijQHxNPbumI4A7FqcAvj2Rs5fOR7OJXj5F10ZalglFunbCNtJ9jDy3Lvj96jAYouFFlNpKZWOxYVnJ7ra2rrqjhJk8b1RfOTG05/CTNgwGir89raTA9VZiO2OX/9gXkX7zl9B/wyIOJ+GrUjTVFkdG1LAKkyjTBWUU9wAkOvmFJYXwZZG0JYN7P+RkizqjRYHRlCehmrwvx/gPfPLExluiP80GSke0L1TnGuldtRe8DvrGTwHRWoeDbrWcDkuUMzxPWKDgBZTyRCmSVyMYOC3dZWe0HpMzZQq/gcOIxOraxRAHS8DJlvuitBKG9XEznferaitmxKKb8UM2pqGfoDCzujqBsLBmj3+4mAzgRZ78mpqWKA5X5tkIK7w2R72t2rG1sZO54NZUtQDv4tADb2N7dYVPiImajKS+Of2gHhndgvI1FQ8uBCRR0AEQorvBLwD2QaXJSPY8az0M+V7EqToKm6uKl7hqSIWxf4sxpaaVStN3s367yPCmoK6+elbvSEBg0BL7I8pCYoLhEUon6yHI3lD3DcQLyp/fSRk5Nb+If0/ihmTc9LRSXIDBKNTAJ8C6gVNGo6h/vJVbLwhdQfACaOLv032y94gud13FURmD2Jznoln/nV1bLxNoIRbx6KAdBzVjUIVGs8HdaABg8Gt4DJ2LEMYQe1Tl5gXT2IL/bos9IsX5XQwf3wXWmrU9H5j9ft6t5rzdJOznTAYLKKh1M0FwJykphg==
    DATABASE_URL: AgADoc8awMN38X0lBM1g0NOrYrDOSuDMy6gBItmmsrTvogA84q7I5b90jaj9lNL4PyIjt6FpWfWBtVMbWnYT058SWt6QFgRufvB38OG9NriSH4DgXZ80RbPzf+cO0KWsn3OZPlWgTqItx7/760axTDzAwgFC//HvRLZOOMVMUJplFWMR9qW/9K2rCBy1IPQWiuXvfFASZbeyUM73cDIiZgClmWqX146UsRDKO5e4q+Ds6vEMq40ZjBjNIl6UgINYQR/UnjDnNpQO2+f2oCbXm39fF4qScGX4wNPdU5dZPaikWQCfMc1qSIf6brV84Iw+91+TNIYfNU0puSuONeLhuE0i4ro7x2lU303HGFWwbfhodLieFM9uLJpnMJBI4UhnEqVJyLgSweXwjZ7+wH3JpYN1+jQs8Wl/Alt+tV8zFTTwygZ12iRtotI2XNKx3lC5AxJWoFyqHyj1J9LIpdEgdWcAsZedYciplk1JpGVMZ1fVotI/3wvfQEkwiOJIZ220NxbV6tB0mOm6tQg/LxbdJQq8TnRjfAcUEQx2fQ2WLHr7KgXvaNXFBJ1CAsjp/Mcd5+jf9OP9WUMhLDxKjF3MejVziMHusH5SS8mJn/lt7PIXDxlE6qvosEXeN10NO5JgE8UoXHew6YmCioKEpWTrCbd3HVI43gKOlT1a7ClgE/S7f74Yv/oiV4CQd2qLU2rwXKHZVHZ2Ga3qomUbU9QIkbbkN0SXliPgqMhhzAyiZReJmyZ54VWbE9DnPxlMLyANvq6YJiiwl9iXEc6LOeuFG5FwcJnS5+r75FNerTaqCuDef3/O9Q==
  template:
    metadata:
      name: frontend-secrets
      namespace: jobhunt-prod
    type: Opaque
