---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secrets
  namespace: jobhunt-prod
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCrDbAeFvfsOf6NvjX8fT2Nbl4VEJGt8rH9TSsPqUDUcSanR0edx8n00ZDuHwq2FlCLiMHuZ5FduyOIWDHPNO3k6ZfkN9wxbjguGnXWWFKSvJOvE8DaVLKDrLC0E/Dt3Gq/yFyixe8mYqPa49UcXeRT8eqBWs+KO/RFRTGQqArYvtP3RxiYumyYjpw+ecFX9yMzC3M70EM3ywu+rzI6akXiYwSxeCysYI/HVefutokSmBG2i6TltMPcLxP9w0y7O9QYcIJHwNzmyjxUxyKvAb1+hvjQ6dHCK1LAbRIMcOC0XriPvEbtaPE0Jku9rHGePKgiw7r3RUZxAVh1dq805rlWd1hCkz3T7rjyB5AverS+R+qWbNufX0E6ksKvJiPTnGiet/yf+Ik9RRcIKtVzoD5Yo/E8LbqPLq4uiz9G9lcDcoP497NqBfynlToIQOSV0+BIyi3gZt7HYpdgwpkrzUX4xsFa9+4brRCWHo0Z7zBMJbg4XGeNdh518O3b1nQxIjBDItLrGOIi+nHfrdekkrE/sC+Adnh9eUzS9hDaz7m7jpUrbP5jMGcBws6kam3TkiiSOX1xQOYdM2rT7vQMW0QCktGEJLEDzI8reCNWxM9dydN3ollDiawaCsSA0/T9ezCOejRRIPVuzxGmK1B3Bm19of46IMfP1SoeXr2kKqEWoWXh5Y0zFqDymamIH4qUjFIdjpHvwbw/ClUK22SG7BoElS/cuHHVeBf0evMDd9fnzjIlrBZ122djkwkk+g==
    MINIO_ROOT_USER: AgBONWBjErnvxheGDxqizlBC7k6HXfnPXxi6Kghqpm8Oto/mwyXTRNncelxQqwdp18Utrmqc8KA5Z2LbqQa/r95sx6hd1a/PxY/VK/pNkJyyT9i0vi9e7fuEB5UEb7BYNrcWzXAbVKsa1kCQZ1HCeJbbL8qcgPJfsp8BMhBieAB5Y/ShIdB6GnE8yny+Grl7mHNEnUmtJnbOHP1pTIXGjL5KJNGNtzDy2BFARKTGQ+RxEYTZFx5XQwRYOgDqFBnSLj0dmj2fSiqtKFYLFWgcNJZksnoo3NzcA+tUprG0jAD6a3dL9BpuYtYYSvd6A1pUVVC66aL9KRtX7QSABiva+hKBfaam1m6O41YWT2TD4oGEPLJzC7MesjGIOuAiGsRHDFGVbDiOFAsCmWHYmODvVmxJHIKsy4kSpkpSHrhNXyEQFhwO1f1+v1IrN5GgkEcEq4d4v7OI2JU7LKT1Ergo8qlKDL0iOH6fsImIaeQu6HC9dE4fJJ1Q+nRTW6RHOySQD276/egOK6GgPNfq7pco8AEv84AdJ6rTkc3VhxkZFINDg35oiV085hRCRwBK8s2y1sxiVYruDp3t9GUsqLQiJ/SLoIA+1I3w8X3JIazyf/GBBj2g9yTTZeni0fLs0szo0gbNn51jCUVXQ9fsb04Xh/NiTiWztc45d5ac7YPmdkCZoT/Upkb53zWVjRLw2Abjdzq+cMDCbgi7ibbNaWCTV1E2fVrVS04xV28=
  template:
    metadata:
      name: minio-secrets
      namespace: jobhunt-prod
